# Generated by Django 5.1.6 on 2025-07-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='N/A', max_length=250),
            preserve_default=False,
        ),
    ]
